;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        abort-recursive-edit
        beginning-of-buffer
        beginning-of-visual-line
        electric-newline-and-maybe-indent
        end-of-buffer
        eval-last-sexp
        eval-print-last-sexp
        forward-sentence
        indent-for-tab-command
        iy-go-to-char--command
        kill-region
        markdown-exdent-or-delete
        org-backward-paragraph
        org-beginning-of-line
        org-cycle
        org-delete-char
        org-end-of-line
        org-force-self-insert
        org-kill-line
        org-metaleft
        org-metaright
        org-self-insert-command
        org-shiftleft
        org-shiftright
        org-shifttab
        org-time-stamp-inactive
        org-yank
        ))

(setq mc/cmds-to-run-once
      '(
        describe-key
        enlarge-window-horizontally
        find-file
        suspend-frame
        switch-to-buffer
        undo-tree-visualize
        ))
