;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-buffer
        beginning-of-visual-line
        electric-newline-and-maybe-indent
        enlarge-window
        enlarge-window-horizontally
        eval-print-last-sexp
        indent-for-tab-command
        kill-region
        shrink-window
        shrink-window-horizontally
        ))

(setq mc/cmds-to-run-once
      '(
        markdown-exdent-or-delete
        ))
