;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        LaTeX-insert-left-brace
        delete-horizontal-space
        electric-newline-and-maybe-indent
        indent-for-tab-command
        kill-region
        kill-sentence
        kill-sexp
        markdown-electric-backquote
        markdown-exdent-or-delete
        org-beginning-of-line
        org-cycle
        org-delete-char
        org-end-of-line
        org-force-self-insert
        org-kill-line
        org-metaleft
        org-metaright
        org-return-indent
        org-self-insert-command
        org-set-tags-command
        org-shiftcontrolleft
        org-shiftcontrolright
        org-shiftleft
        org-shiftmetaright
        org-shiftright
        org-shifttab
        org-yank
        prelude-move-beginning-of-line
        sp-backward-delete-char
        sp-delete-char
        sp-kill-hybrid-sexp
        ))

(setq mc/cmds-to-run-once
      '(
        indent-rigidly
        indent-rigidly-left
        toggle-input-method
        ))
